/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/new_workspace.glb --typescript --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Monitor1_1: THREE.Mesh;
    Monitor1_2: THREE.Mesh;
    KeyboardNotebook1: THREE.Mesh;
    ScreenNotebok1_1: THREE.Mesh;
    ScreenNotebok1_2: THREE.Mesh;
    Mouse: THREE.Mesh;
    desk: THREE.Mesh;
    Cube002_Cube003: THREE.Mesh;
    Cube003_Cube004: THREE.Mesh;
    Cube004_Cube005: THREE.Mesh;
    Cube005_Cube006: THREE.Mesh;
    Cube006_Cube007: THREE.Mesh;
    Cube007_Cube008: THREE.Mesh;
    Cube_Cube001: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Cylinder013: THREE.Mesh;
    Plane001_Plane002: THREE.Mesh;
    ["Node-Mesh003"]: THREE.Mesh;
    ["Node-Mesh003_1"]: THREE.Mesh;
    ["Node-Mesh003_2"]: THREE.Mesh;
    Keyboard1: THREE.Mesh;
    rugSquare_2: THREE.Mesh;
    rugSquare_2_1: THREE.Mesh;
    rugSquare_3: THREE.Mesh;
    rugSquare_3_1: THREE.Mesh;
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane002: THREE.Mesh;
    Plane002_1: THREE.Mesh;
    Plane002_2: THREE.Mesh;
    Plane002_3: THREE.Mesh;
    Plane002_4: THREE.Mesh;
  };
  materials: {
    Plastic1Monitor1: THREE.MeshStandardMaterial;
    Screen1Monitor1: THREE.MeshStandardMaterial;
    Keyboard1Notebook1: THREE.MeshStandardMaterial;
    Plastic1Notebook1: THREE.MeshStandardMaterial;
    Screen1Notebook1: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    BlackCoatSteel: THREE.MeshStandardMaterial;
    GrayPlastic: THREE.MeshStandardMaterial;
    WhiteSteelScrew: THREE.MeshStandardMaterial;
    BlackPlastic: THREE.MeshStandardMaterial;
    BlackWood: THREE.MeshStandardMaterial;
    mat22: THREE.MeshStandardMaterial;
    mat9: THREE.MeshStandardMaterial;
    mat20: THREE.MeshStandardMaterial;
    ["lambert3SG.001"]: THREE.MeshStandardMaterial;
    carpet: THREE.MeshStandardMaterial;
    carpetDarker: THREE.MeshStandardMaterial;
    ["Brick wall"]: THREE.MeshStandardMaterial;
    ["Wood Floor Distressed Pale Oak"]: THREE.MeshStandardMaterial;
    ["chrome metal"]: THREE.MeshStandardMaterial;
    ["plastic black rough"]: THREE.MeshStandardMaterial;
    fabric: THREE.MeshStandardMaterial;
    ["metal painted"]: THREE.MeshStandardMaterial;
    ["plastic smooth"]: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function NewWorkspace(props: React.ComponentProps<"group">) {
  const { nodes, materials } = useGLTF(
    "models/new_workspace.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.363, 1.204, -1.657]} scale={[1.608, 1.274, 1]}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.Monitor1_1.geometry}
            material={materials.Plastic1Monitor1}
          />
          <mesh
            geometry={nodes.Monitor1_2.geometry}
            material={materials.Screen1Monitor1}
          />
        </group>
      </group>
      <group position={[0.741, 1.019, -1.464]} rotation={[0, -0.777, 0]}>
        <mesh
          geometry={nodes.KeyboardNotebook1.geometry}
          material={materials.Keyboard1Notebook1}
          position={[0.056, -0.059, 0.13]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        />
        <group
          position={[0.056, -0.042, -0.044]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={100}
        >
          <mesh
            geometry={nodes.ScreenNotebok1_1.geometry}
            material={materials.Plastic1Notebook1}
          />
          <mesh
            geometry={nodes.ScreenNotebok1_2.geometry}
            material={materials.Screen1Notebook1}
          />
        </group>
      </group>
      <group position={[0.01, 0.946, -1.292]}>
        <mesh
          geometry={nodes.Mouse.geometry}
          material={materials["Material.001"]}
          scale={100}
        />
      </group>
      <mesh
        geometry={nodes.desk.geometry}
        material={materials.BlackCoatSteel}
        position={[0, 0, -1.475]}
        rotation={[-0.397, -1.566, -0.397]}
        scale={[1, 1, 1.284]}
      >
        <mesh
          geometry={nodes.Cube002_Cube003.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cube003_Cube004.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cube004_Cube005.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cube005_Cube006.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cube006_Cube007.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cube007_Cube008.geometry}
          material={materials.GrayPlastic}
        />
        <mesh
          geometry={nodes.Cube_Cube001.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder001.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder002.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder003.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder004.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder005.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder006.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder007.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder008.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder009.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder010.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Cylinder011.geometry}
          material={materials.BlackPlastic}
        />
        <mesh
          geometry={nodes.Cylinder012.geometry}
          material={materials.WhiteSteelScrew}
        />
        <mesh
          geometry={nodes.Cylinder013.geometry}
          material={materials.BlackCoatSteel}
        />
        <mesh
          geometry={nodes.Plane001_Plane002.geometry}
          material={materials.BlackWood}
        />
      </mesh>
      <group position={[1.649, 0.37, -1.664]} scale={[1.287, 1, 1.287]}>
        <mesh
          geometry={nodes["Node-Mesh003"].geometry}
          material={materials.mat22}
        />
        <mesh
          geometry={nodes["Node-Mesh003_1"].geometry}
          material={materials.mat9}
        />
        <mesh
          geometry={nodes["Node-Mesh003_2"].geometry}
          material={materials.mat20}
        />
      </group>
      <mesh
        geometry={nodes.Keyboard1.geometry}
        material={materials["lambert3SG.001"]}
        position={[-0.355, 0.935, -1.302]}
        scale={0.001}
      />
      <group position={[0.958, 0, 0]} scale={[2.053, 1, 1]}>
        <mesh
          geometry={nodes.rugSquare_2.geometry}
          material={materials.carpet}
        />
        <mesh
          geometry={nodes.rugSquare_2_1.geometry}
          material={materials.carpetDarker}
        />
        <mesh
          geometry={nodes.rugSquare_3.geometry}
          material={materials.carpetDarker}
        />
        <mesh
          geometry={nodes.rugSquare_3_1.geometry}
          material={materials.carpet}
        />
      </group>
      <group scale={[1.982, 1, 1.982]}>
        <mesh
          geometry={nodes.Plane_1.geometry}
          material={materials["Brick wall"]}
        />
        <mesh
          geometry={nodes.Plane_2.geometry}
          material={materials["Wood Floor Distressed Pale Oak"]}
        />
      </group>
      <group position={[-0.322, 0, -0.567]} scale={[1.296, 1.296, 1]}>
        <mesh
          geometry={nodes.Plane002.geometry}
          material={materials["chrome metal"]}
        />
        <mesh
          geometry={nodes.Plane002_1.geometry}
          material={materials["plastic black rough"]}
        />
        <mesh
          geometry={nodes.Plane002_2.geometry}
          material={materials.fabric}
        />
        <mesh
          geometry={nodes.Plane002_3.geometry}
          material={materials["metal painted"]}
        />
        <mesh
          geometry={nodes.Plane002_4.geometry}
          material={materials["plastic smooth"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/new_workspace.glb");
