/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/workspace.glb --types --transform 
Files: public/models/workspace.glb [98.87MB] > /Users/sauravlalkarn/Projects/personal/portfolio/workspace-transformed.glb [12.09MB] (88%)
*/

import * as THREE from "three";
import React, { JSX } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Plane_1: THREE.Mesh;
    Plane_2: THREE.Mesh;
    Plane_3: THREE.Mesh;
    Cube010_1: THREE.Mesh;
    Cube010_2: THREE.Mesh;
    Circle_1: THREE.Mesh;
    Circle_2: THREE.Mesh;
    Cube: THREE.Mesh;
    Cube010: THREE.Mesh;
    Plane004: THREE.Mesh;
    Plane004_1: THREE.Mesh;
    Plane004_2: THREE.Mesh;
    Plane008: THREE.Mesh;
    Mesh005: THREE.Mesh;
    Mesh005_1: THREE.Mesh;
    Mesh005_2: THREE.Mesh;
    Mesh005_3: THREE.Mesh;
    Plane001_1: THREE.Mesh;
    Plane001_2: THREE.Mesh;
    Plane001_3: THREE.Mesh;
    Plane001_4: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane003_1: THREE.Mesh;
    Plane003_2: THREE.Mesh;
    Plane003_3: THREE.Mesh;
    body: THREE.Mesh;
    buttons: THREE.Mesh;
    keys: THREE.Mesh;
    Icosphere: THREE.Mesh;
    Icosphere_1: THREE.Mesh;
    Cube086: THREE.Mesh;
    Whiteboard001: THREE.Mesh;
  };
  materials: {
    ["Old varnished wooden floor"]: THREE.MeshStandardMaterial;
    ["Wall bricks"]: THREE.MeshStandardMaterial;
    PaletteMaterial001: THREE.MeshStandardMaterial;
    Wood: THREE.MeshStandardMaterial;
    PaletteMaterial002: THREE.MeshStandardMaterial;
    Plastic: THREE.MeshStandardMaterial;
    ShinyPlastic: THREE.MeshStandardMaterial;
    LeatherCougar2: THREE.MeshStandardMaterial;
    LeatherCougar: THREE.MeshStandardMaterial;
    ["Leather.001"]: THREE.MeshStandardMaterial;
    ["Leather.002"]: THREE.MeshStandardMaterial;
    Leather: THREE.MeshStandardMaterial;
    Belt: THREE.MeshStandardMaterial;
    pot: THREE.MeshStandardMaterial;
    soil21: THREE.MeshStandardMaterial;
    ["Leaf plant"]: THREE.MeshStandardMaterial;
    ["BODY Plant"]: THREE.MeshStandardMaterial;
    Stick: THREE.MeshStandardMaterial;
    ["SUMSUNG logo"]: THREE.MeshStandardMaterial;
    LCD: THREE.MeshStandardMaterial;
    Metal: THREE.MeshStandardMaterial;
    MB_keyboard: THREE.MeshStandardMaterial;
    MB_metal: THREE.MeshStandardMaterial;
    ["MB_gray logo"]: THREE.MeshStandardMaterial;
    MB_desktop: THREE.MeshStandardMaterial;
    PaletteMaterial003: THREE.MeshStandardMaterial;
    PaletteMaterial004: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    PaletteMaterial005: THREE.MeshPhysicalMaterial;
    PaletteMaterial006: THREE.MeshStandardMaterial;
    PaletteMaterial007: THREE.MeshStandardMaterial; // Renamed from PaletteMaterial001 to avoid duplicate
    WB_Wood: THREE.MeshStandardMaterial;
  };
  animations: THREE.AnimationClip[];
};

export function Workspace(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "models/workspace-transformed.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.12, 0.752, -1.384]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[1.378, 1, 1]}
      >
        <mesh geometry={nodes.Cube010_1.geometry} material={materials.Wood} />
        <mesh
          geometry={nodes.Cube010_2.geometry}
          material={materials.PaletteMaterial002}
        />
      </group>
      <group
        position={[-0.4, 0.698, -0.829]}
        rotation={[-Math.PI, 0.353, -Math.PI / 2]}
        scale={0.034}
      >
        <mesh geometry={nodes.Circle_1.geometry} material={materials.Plastic} />
        <mesh
          geometry={nodes.Circle_2.geometry}
          material={materials.ShinyPlastic}
        />
      </group>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.LeatherCougar2}
        position={[-0.492, 1.091, -0.313]}
        rotation={[3.1, 0.003, -3.141]}
        scale={0.088}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={materials.LeatherCougar}
        position={[-0.497, 0.59, -0.432]}
        rotation={[-2.938, 0.003, 3.141]}
        scale={0.283}
      />
      <group
        position={[-0.496, 0.626, -0.579]}
        rotation={[Math.PI / 2, 0, -3.139]}
        scale={0.283}
      >
        <mesh
          geometry={nodes.Plane004.geometry}
          material={materials["Leather.001"]}
        />
        <mesh
          geometry={nodes.Plane004_1.geometry}
          material={materials["Leather.002"]}
        />
        <mesh
          geometry={nodes.Plane004_2.geometry}
          material={materials.Leather}
        />
      </group>
      <mesh
        geometry={nodes.Plane008.geometry}
        material={materials.Belt}
        position={[-0.496, 0.626, -0.579]}
        rotation={[Math.PI / 2, 0, -3.139]}
        scale={0.281}
      />
      <group position={[1.596, 0.203, -1.48]}>
        <mesh geometry={nodes.Mesh005.geometry} material={materials.pot} />
        <mesh geometry={nodes.Mesh005_1.geometry} material={materials.soil21} />
        <mesh
          geometry={nodes.Mesh005_2.geometry}
          material={materials["Leaf plant"]}
        />
        <mesh
          geometry={nodes.Mesh005_3.geometry}
          material={materials["BODY Plant"]}
        />
      </group>
      <group position={[-0.662, 0.865, -1.559]} scale={[1.299, 1.203, 1]}>
        <mesh geometry={nodes.Plane001_1.geometry} material={materials.Stick} />
        <mesh
          geometry={nodes.Plane001_2.geometry}
          material={materials["SUMSUNG logo"]}
        />
        <mesh geometry={nodes.Plane001_3.geometry} material={materials.LCD} />
        <mesh geometry={nodes.Plane001_4.geometry} material={materials.Metal} />
      </group>
      <group
        position={[0.09, 0.865, -1.381]}
        rotation={[0, -0.854, 0]}
        scale={[1.225, 1, 1.094]}
      >
        <mesh
          geometry={nodes.Plane003.geometry}
          material={materials.MB_keyboard}
        />
        <mesh
          geometry={nodes.Plane003_1.geometry}
          material={materials.MB_metal}
        />
        <mesh
          geometry={nodes.Plane003_2.geometry}
          material={materials["MB_gray logo"]}
        />
        <mesh
          geometry={nodes.Plane003_3.geometry}
          material={materials.MB_desktop}
        />
      </group>
      <mesh
        geometry={nodes.body.geometry}
        material={materials.PaletteMaterial003}
        position={[-0.694, 0.876, -1.292]}
        rotation={[0.094, 0, 0]}
        scale={[1.236, 1, 1]}
      />
      <mesh
        geometry={nodes.buttons.geometry}
        material={materials.PaletteMaterial004}
        position={[-0.296, 0.872, -1.283]}
        scale={[1.236, 1, 1]}
      />
      <mesh
        geometry={nodes.keys.geometry}
        material={materials["Material.021"]}
        position={[-0.641, 0.886, -1.334]}
        rotation={[0.094, 0, 0]}
        scale={[1.236, 1, 1.197]}
      />
      <group
        position={[-0.45, 0.887, -1.348]}
        rotation={[0.094, 0, 0]}
        scale={[1.236, 1, 1]}
      >
        <mesh
          geometry={nodes.Icosphere.geometry}
          material={materials.PaletteMaterial005}
        />
        <mesh
          geometry={nodes.Icosphere_1.geometry}
          material={materials.PaletteMaterial006}
        />
      </group>
      <mesh
        geometry={nodes.Cube086.geometry}
        material={materials.PaletteMaterial001}
        position={[0.562, 0.984, -1.602]}
        rotation={[1.581, 0.004, -1.57]}
        scale={[1.125, 1.025, 1]}
      />
      <mesh
        geometry={nodes.Whiteboard001.geometry}
        material={materials.WB_Wood}
        position={[-0.522, 2.45, -1.973]}
        rotation={[-0.002, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane_1.geometry}
        material={materials["Old varnished wooden floor"]}
      />
      <mesh
        geometry={nodes.Plane_2.geometry}
        material={materials["Wall bricks"]}
      />
      <mesh
        geometry={nodes.Plane_3.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  );
}

useGLTF.preload("models/workspace-transformed.glb");

export default Workspace;
